# Generated by Django 4.1.7 on 2023-08-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='created_by',
        ),
    ]
